container:
  image: cirrusci/android-sdk:26
  cpu: 4
  memory: 10G

test_task:
  android_cache:
    folder: ~/.android/build-cache
  test_script:
    - ./gradlew --stacktrace connectedCheck -x okreplay-gradle-plugin:test -x okreplay-sample:connectedAndroidTest