language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - extra-android-m2repository
    - android-27
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - GRADLE_OPTS="-Xmx2048m -XX:MaxPermSize=1024m"
    - secure: "pOB4fwrSQDMJPLsHxbsbUQZnN335w+1/3e5TQ/8lwHK0aUuM1jkDFOLsVaXsS2a+YzOXL40X3kMoyiAx5N1ikbk8TDwGqXZ6tSsFFw376oWWXrWyZ/56Yp5FGuMSmBBygpZoFw4VATZX+JL8RLpAdJbRtKzxmzg8X/QDK97X6et18PsqAFL6xV8iZ/EIHhATAUwjCy6jqI4fZXpWQjNtizePQODUgokDd7ycIXpjtvPmdO8BadI5n8Zmh1QV53a7TrbEbQ+yFPkFDuvL1Xoanld/Lyc6xlTbZkWGayM6Z6vzi9VFDswA3tf28P8nZW7XSXOewI7DXeRP/RKSyPlNmghnbIEX5hpNB5y/YObEgUNzSR6tv5mdkwz2rs/kNkmpdNpwk8m+s0QpBEdeqn7+GWHq5g6h7wWIxP+tRvX8EW99lstx8D6pSbBL0NGP33G8Sg2hReATsUE63YGMUKVEZUex0s9eDOFoLtFE0uKLi3N1q9C7iDlHEs9idoXbKvM8Ha+cj9NuQrQfDzDIXRGFo2Gme1OyWbqgmlyDI4aCKXYgWwbHk+IpIIpNI+UTUYyz/5IdO+FMY8ocf+XNWvquYeC+lZtU/YoZnadfDCuAtnd6JpUToElL6Fz/pZCAj8Us4sYftL/V26Xt8EEQqYCnXMBb1ATq50naFvkk05e1k98="
    - secure: "bDlD8/RjM2Ic9bf87Yj3Pygla1nQwyyP9Mp0RslCssCkUx+6ZIeOS+E+AZN+j5GtDoLIMhZQw6wwDfFewSb+Txfc8AUJmD+gOjuJrki2XAiQfI9QdmbT8FHH0Oyv4dC94S0/JwPSm0uOiXwfBcJMKWMIC6FOtGJgRY2/+ReEr9H66RaycXlTRqKAusSIJERO7JaVTYTNZ6bG7fC51C9bfVwQZfzOfluICWFfWQF2z7VqUlCQUKRkBBBC80pCvzotJE+YLmvOw/CiqP00JMv4PtnpiqccfQa7N/s+dm6978kIz9nrL0Pn6c2gq8mIuML85AicTw6srs9cSJvUQ1CLvoToGjRYpIXW8qlr7dMjLYt5MCnWHE0ECQ0iBgKCcNUSwiB3pWjCM3jXPhPGuSd92mP0MC6Kpf8cJy+ObQnWQQjMSEBo8hRPhYMVpg84AERQKRCbZLtmk1wuV9eCeovmgriraGvsLZ64qNzDCl6awuTeHintqHH9rPj0I1k0xNs/DRNxPZAkv+ITSoGQoU1ZCf9id5PLdrkYf3TtgUvaFI+YN+b170tl2T0I0Dlb8Pzt/Akl8kXRxQtmlQ0MwNmTOBaFWVWHfFpBpR2xq+yS+SoVf9eEC696KVAOdivMxGY2qXMitY3/2PUuUcB2RT2oFAb5KhctkBMNiHgngqp0nfY="

branches:
  except:
    - gh-pages

notifications:
  email: false

script:
  - ./gradlew connectedCheck --stacktrace --max-workers=2 -x okreplay-sample:connectedAndroidTest

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

addons:
  artifacts: true
