name: Deploy snapshot

on:
  # Trigger ONLY on push to master branch
  push:
    branches:
      - master
jobs:
  build-test:
    uses: ./.github/workflows/build_test.yml@master
  deploy-snapshot:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout okreplay
        uses: actions/checkout@v2
      - name: Deploy new snapshot of okreplay
        shell: bash
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.NEXUS_USER }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew uploadArchives
